# 퍼셉트론 구현하기

## 간단한 구현

In [5]:
# x1과 x2를 인수로 받는 AND라는 함수입니다.

In [6]:
def AND(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.7 # w1, w2 ,theta는 함수 안에서 초기화
    tmp = x1*w1 + x2*w2
# 가중치를 곱한 입력의 총합이 임계값을 넘으면 1을 반환하고 그 외에는 0을 반환한다.
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1

In [7]:
AND(0,0) # 0을 출력

0

In [8]:
AND(1,0) # 0을 출력

0

In [9]:
AND(0,1) # 0을 출력

0

In [10]:
AND(1,1) # 0을 출력

1

## 가중치와 편향 도입

In [1]:
import numpy as np

In [2]:
x = np.array([0,1])
x

array([0, 1])

In [4]:
w = np.array([0.5, 0.5])
w

array([0.5, 0.5])

In [5]:
b = -0.7 # b = bias

In [6]:
w*x # 넘파이 배열끼리의 곱셈은 두 배열의 원소 수가 같다면 각 원소끼리 곱합니다.

array([0. , 0.5])

In [7]:
np.sum(w*x)

0.5

In [8]:
np.sum(w*x) + b

-0.19999999999999996

## 가중치와 편향 구현하기

'가중치와 편향을 도입'한 AND 게이트는 다음과 같이 구현할 수 있습니다.

#### AND 게이트

In [9]:
def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7 # 뉴런이 얼마나 쉽게 활성화(결과로 1을 출력) 하느냐를 조정하는 매개변수
    # for example, b = -0.1이면 각 입력 신호에 가중치를 곱한 값들의 합이 0.1을 초과할 때만 뉴런이 활성화 합니다.
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    elif tmp > 0:
        return 1

#### NAND 게이트

In [ ]:
def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-0.5, -0.5]) # AND와는 가중치(w와 b)만 다르다!
    b = 0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

#### OR 게이트

In [ ]:
def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.2
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1